/** @type { import('cz-git').UserConfig['prompt'] } */
export default {
  alias: { fd: 'docs: fix typos' },
  messages: {
    type: "Select the type of change that you're committing:",
    scope: 'Denote the SCOPE of this change (optional):',
    customScope: 'Denote the SCOPE of this change:',
    subject: 'Write a SHORT, IMPERATIVE tense description of the change:\n',
    body: 'Provide a LONGER description of the change (optional). Use "|" to break new line:\n',
    breaking:
      'List any BREAKING CHANGES (optional). Use "|" to break new line:\n',
    footerPrefixesSelect:
      'Select the ISSUES type of changeList by this change (optional):',
    customFooterPrefix: 'Input ISSUES prefix:',
    footer: 'List any ISSUES by this change. E.g.: #31, #34:\n',
    generatingByAI: 'Generating your AI commit subject...',
    generatedSelectByAI: 'Select suitable subject by AI generated:',
    confirmCommit: 'Are you sure you want to proceed with the commit above?',
  },
  types: [
    { value: 'feat', name: 'feat:     ✨  新功能', emoji: ':sparkles:' },
    { value: 'fix', name: 'fix:      🐛  修复bug', emoji: ':bug:' },
    {
      value: 'docs',
      name: 'docs:     📝  仅文档更改',
      emoji: ':memo:',
    },
    {
      value: 'style',
      name: 'style:    💄  不影响代码含义的更改',
      emoji: ':lipstick:',
    },
    {
      value: 'refactor',
      name: 'refactor: ♻️   既不修复bug也不添加功能的代码更改',
      emoji: ':recycle:',
    },
    {
      value: 'perf',
      name: 'perf:     ⚡️  提高性能的代码更改',
      emoji: ':zap:',
    },
    {
      value: 'test',
      name: 'test:     ✅  添加缺失的测试或修正现有的测试',
      emoji: ':white_check_mark:',
    },
    {
      value: 'build',
      name: 'build:    📦️   影响构建系统或外部依赖的更改',
      emoji: ':package:',
    },
    {
      value: 'ci',
      name: 'ci:       🎡  CI配置文件和脚本的更改',
      emoji: ':ferris_wheel:',
    },
    {
      value: 'chore',
      name: 'chore:    🔨  不修改src或test文件的其他更改',
      emoji: ':hammer:',
    },
    {
      value: 'revert',
      name: 'revert:   ⏪️  还原之前的提交',
      emoji: ':rewind:',
    },
  ],
  useEmoji: false,
  emojiAlign: 'center',
  useAI: false,
  aiNumber: 1,
  themeColorCode: '',
  scopes: [],
  allowCustomScopes: true,
  allowEmptyScopes: true,
  customScopesAlign: 'bottom',
  customScopesAlias: 'custom',
  emptyScopesAlias: 'empty',
  upperCaseSubject: false,
  markBreakingChangeMode: false,
  allowBreakingChanges: ['feat', 'fix'],
  breaklineNumber: 100,
  breaklineChar: '|',
  skipQuestions: [],
  issuePrefixes: [
    { value: 'closed', name: 'closed:   ISSUES has been processed' },
  ],
  customIssuePrefixAlign: 'top',
  emptyIssuePrefixAlias: 'skip',
  customIssuePrefixAlias: 'custom',
  allowCustomIssuePrefix: true,
  allowEmptyIssuePrefix: true,
  confirmColorize: true,
  maxHeaderLength: Infinity,
  maxSubjectLength: Infinity,
  minSubjectLength: 0,
  scopeOverrides: undefined,
  defaultBody: '',
  defaultIssues: '',
  defaultScope: '',
  defaultSubject: '',
};
