// @ts-nocheck -- skip type checking
import * as docs_9 from "../content/docs/webpack/module.mdx?collection=docs&hash=1744791348953"
import * as docs_8 from "../content/docs/webpack/build.mdx?collection=docs&hash=1744791348953"
import * as docs_7 from "../content/docs/react/useState.mdx?collection=docs&hash=1744791348953"
import * as docs_6 from "../content/docs/react/scheduler.mdx?collection=docs&hash=1744791348953"
import * as docs_5 from "../content/docs/react/hook.mdx?collection=docs&hash=1744791348953"
import * as docs_4 from "../content/docs/react/fiber.mdx?collection=docs&hash=1744791348953"
import * as docs_3 from "../content/docs/react/event.mdx?collection=docs&hash=1744791348953"
import * as docs_2 from "../content/docs/react/dom.mdx?collection=docs&hash=1744791348953"
import * as docs_1 from "../content/docs/update.mdx?collection=docs&hash=1744791348953"
import * as docs_0 from "../content/docs/index.mdx?collection=docs&hash=1744791348953"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"index.mdx","absolutePath":"/Users/haoran/Desktop/thresslee-docs/content/docs/index.mdx"}, data: docs_0 }, { info: {"path":"update.mdx","absolutePath":"/Users/haoran/Desktop/thresslee-docs/content/docs/update.mdx"}, data: docs_1 }, { info: {"path":"react/dom.mdx","absolutePath":"/Users/haoran/Desktop/thresslee-docs/content/docs/react/dom.mdx"}, data: docs_2 }, { info: {"path":"react/event.mdx","absolutePath":"/Users/haoran/Desktop/thresslee-docs/content/docs/react/event.mdx"}, data: docs_3 }, { info: {"path":"react/fiber.mdx","absolutePath":"/Users/haoran/Desktop/thresslee-docs/content/docs/react/fiber.mdx"}, data: docs_4 }, { info: {"path":"react/hook.mdx","absolutePath":"/Users/haoran/Desktop/thresslee-docs/content/docs/react/hook.mdx"}, data: docs_5 }, { info: {"path":"react/scheduler.mdx","absolutePath":"/Users/haoran/Desktop/thresslee-docs/content/docs/react/scheduler.mdx"}, data: docs_6 }, { info: {"path":"react/useState.mdx","absolutePath":"/Users/haoran/Desktop/thresslee-docs/content/docs/react/useState.mdx"}, data: docs_7 }, { info: {"path":"webpack/build.mdx","absolutePath":"/Users/haoran/Desktop/thresslee-docs/content/docs/webpack/build.mdx"}, data: docs_8 }, { info: {"path":"webpack/module.mdx","absolutePath":"/Users/haoran/Desktop/thresslee-docs/content/docs/webpack/module.mdx"}, data: docs_9 }], [{ info: {"path":"meta.json","absolutePath":"/Users/haoran/Desktop/thresslee-docs/content/docs/meta.json"}, data: {"title":"Ran Docs","pages":["index","react","webpack","[Triangle][Vercel](https://vercel.com)"],"root":true} }])