import { RootProvider } from 'fumadocs-ui/provider';
import type { Metadata } from 'next';
import { Geist_Mono, Inter } from 'next/font/google';

import './globals.css';

import { Providers } from './providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script type="application/ld+json" />
      </head>
      <body className="flex flex-col min-h-dvh">
        <RootProvider theme={{ defaultTheme: 'dark' }}>
          <Providers>{children}</Providers>
        </RootProvider>
      </body>
    </html>
  );
}
